### ISSUE TITLE
How to customize log level?

### ISSUE THREAD

**Issue by mugli** [alexandrebodin/hapi-good-winston#1]
I want to disable ops logs. How do I send that argument to `hapi-good-winston`? 
An example in the project readme would be great. 

Thanks!

**Comment by alexandrebodin** [comment]
Hi thanks for the feedback.

Currently you won't be able to customize log level (choosing for an event which logging level to use). I'll be working on that very soon.

But you can disable logs using [Good Squeeze](https://github.com/hapijs/good-squeeze) to filter.

I'll add some more examples in a coming release thanks !

**Comment by alexandrebodin** [comment]
Using the example below you can log ops with the first reporter and only log response events with the second one.

``` javascript
const options = {
    ops: {
        interval: 1000,
    },
    reporters: {
        winston: [goodWinston(winston)],
        winstonWithOps: [
            {
                module: 'good-squeeze',
                name: 'Squeeze',
                args: [{ response: '*'}]
            },
            goodWinston(winston)
        ]
    },
};
```
