### ISSUE TITLE
Good dependency deprecated

### ISSUE THREAD

**Issue by csmatheusgaldino** [alexandrebodin/hapi-good-winston#10]
`@hapi/good` dependency got deprecated since December 2019 according to [package description](https://github.com/hapijs/good)

**Comment by alexandrebodin** [comment]
Hi, I saw that. I don't really have much to propose here 🤷  I'm not going to deprecate this package as it still works with good as it is. This will eventually end up out of date on its own I think.

I'm going to close this. If you have some ideas let me know please :)
