### ISSUE TITLE
Support for winston > 3.x

### ISSUE THREAD

**Issue by javix** [alexandrebodin/hapi-good-winston#6]
Hi,

I get the following warning.

> hapi-good-winston@2.0.1 requires a peer of winston@>=2.x <3.x but none is installed. You must install peer dependencies yourself.

It is possible to update the winston version?

**Comment by alexandrebodin** [comment]
@javix I was on holiday the last few days. I'll try and release a new version this week or the next :)

**Comment by alexandrebodin** [comment]
@javix As of v2.1.0 winston 3.x is allowed as peer dep ;)
